version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
  backend:
  frontend:

networks:
  mynetworks:

volumes: #docker voce vai poder olhar esse path e criar um arquivo aqui
  postgres_data: