# version: '3.8'  # (removido porque é obsoleto)

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

networks:
  mynetwork:   # <- nome corrigido (sem 's')
    driver: bridge

volumes: #docker voce vai poder olhar esse path e criar um arquivo aqui
  postgres_data: